export const ENV_VARS = {
  PORT: 'PORT',
};

export const MONGO_VARS = {
  MONGO_DB_USER: 'MONGO_DB_USER',
  MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
  MONGO_DB_URI: 'MONGO_DB_URI',
  MONGO_DB_COLLECTION: 'MONGO_DB_COLLECTION',
};
