openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of students app
tags:
  - name: Students
    description: Operation about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: <http://localhost:3000>
  - url: <https://example.com/api/v1>
paths:
  /students/{id}:
    get:
      $ref: ../swagger/paths/students/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/students/{id}/patch.yaml
  /students:
    post:
      $ref: ../swagger/paths/students/post.yaml
    get:
      $ref: ../swagger/paths/students/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
